In [1]:
import numpy as np
import pandas as pd
from splinter import Browser
from bs4 import BeautifulSoup as bs
import time
from html.parser import HTMLParser
import re

In [2]:
def init_browser():
    executable_path = {"executable_path": "/usr/local/bin/chromedriver"}
    return Browser("chrome", **executable_path, headless=False)

In [3]:
def scrape_nasa_title():
    browser = init_browser()

    # scrape nasa url
    url = "https://mars.nasa.gov/news/?page=0&per_page=40&order=publish_date+desc%2Ccreated_at+desc&search=&category=19%2C165%2C184%2C204&blank_scope=Latest"
    browser.visit(url)

    time.sleep(3)

    # Scrape page into Soup
    html = browser.html
    soup = bs(html, "html.parser")

    # Get article title
    article = soup.find_all('div', class_='content_title')

    # Close the browser after scraping
    browser.quit()

    # Return results
    return article

In [4]:
articles = scrape_nasa_title()

In [5]:
# function to remove html tags https://medium.com/@jorlugaqui/how-to-strip-html-tags-from-a-string-in-python-7cb81a2bbf44
def remove_html_tags(text):
    clean = re.compile('<.*?>')
    return re.sub(clean, '', text)
# call function and convert object to string using __repr__
check = remove_html_tags(articles.__repr__())

# format data and split on any ,
save = check.split(",")
title_clean = save

# # create and clean new dataframe
title_clean = pd.DataFrame(title_clean)
title_clean.columns = ['title']
title_clean
title_df = title_clean.drop([0, 13, 15, 32, 38, 39, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58])
title_df.reset_index(drop=True, inplace=True)
title_df

                                                title
0    Virginia Middle School Student Earns Honor of...
1    NASA's Curiosity Mars Rover Snaps Its Highest...
2          NASA to Reveal Name of Its Next Mars Rover
3                   The MarCO Mission Comes to an End
4    A Year of Surprising Science From NASA's InSi...
5    Mars InSight Lander to Push on Top of the 'Mole'
6             Common Questions about InSight's 'Mole'
7    NASA Adds Return Sample Scientists to Mars 20...
8    NASA's Mars Reconnaissance Orbiter Undergoes ...
9    NASA's Mars 2020 Rover Goes Coast-to-Coast to...
10   NASA Prepares for Moon and Mars With New Addi...
11   NASA Administrator Statement on Moon to Mars ...
12   All About the Laser (and Microphone) Atop Mar...
13   NASA's MAVEN Explores Mars to Understand Radi...
14   Nine Finalists Chosen in NASA's Mars 2020 Rov...
15   NASA's Mars 2020 Rover Closer to Getting Its ...
16     Media Get a Close-Up of NASA's Mars 2020 Rover
17   Space History Is Made in This NASA Robot Factory
18   NASA's Mars 2020 Rover Completes Its First Drive
19   NASA's MAVEN Maps Winds in the Martian Upper ...
20   Newfound Martian Aurora Actually the Most Com...
21          NASA's Treasure Map for Water Ice on Mars
22   Two Rovers to Roll on Mars Again: Curiosity a...
23   NASA's Briefcase-Size MarCO Satellite Picks U...
24   Global Storms on Mars Launch Dust Towers Into...
25   NASA Updates Mars 2020 Mission Environmental ...
26       Two of a Space Kind: Apollo 12 and Mars 2020
27   Mars Scientists Investigate Ancient Life in A...
28   NASA's Mars 2020 Will Hunt for Microscopic Fo...
29      Curiosity Serves Scientists a New One: Oxygen
30       NASA's Mars 2020 Heads Into the Test Chamber
31   Screening Soon: 'The Pathfinders' Trains Lens...
32           InSight's 'Mole' Team Peers into the Pit
33             Mars 2020 Stands on Its Own Six Wheels
34      Naming a NASA Mars Rover Can Change Your Life

In [6]:
def scrape_nasa_body():
    browser = init_browser()

    # scrape nasa url
    url = "https://mars.nasa.gov/news/?page=0&per_page=40&order=publish_date+desc%2Ccreated_at+desc&search=&category=19%2C165%2C184%2C204&blank_scope=Latest"
    browser.visit(url)

    time.sleep(3)

    # Scrape page into Soup
    html = browser.html
    soup = bs(html, "html.parser")

    # get article body
    body = soup.find_all('div', class_='article_teaser_body')
    
    # Close the browser after scraping
    browser.quit()

    # Return results
    return body

In [7]:
bodies = scrape_nasa_body()

In [8]:
# function to remove html tags https://medium.com/@jorlugaqui/how-to-strip-html-tags-from-a-string-in-python-7cb81a2bbf44
def remove_html_tags(text):
    clean = re.compile('<.*?>')
    return re.sub(clean, '', text)
# call function and convert object to string using __repr__
check_bodies = remove_html_tags(bodies.__repr__())

# format data and split on any ,
save_body = check_bodies.replace("[", '').split("., ")
save_body 

# create and clean new dataframe
body_df = pd.DataFrame(save_body)
body_df.columns = ['Body']
body_df.reset_index(drop=True, inplace=True)
body_df

                                                 Body
0   NASA chose a seventh-grader from Virginia as w...
1   After a months-long contest among students to ...
2   A batch of new papers summarizes the lander's ...
3   Engineers have a plan for pushing down on the ...
4   The following Q&amp;As with members of the tea...
5   The leadership council for Mars 2020 science a...
6   Other orbiters will continue relaying data fro...
7   The agency's first step in returning rocks fro...
8   Robotic spacecraft will be able to communicate...
9   Jim Bridenstine addresses NASA's ambitious pla...
10  SuperCam is a rock-vaporizing instrument that ...
11  NASA’s MAVEN spacecraft has discovered “layers...
12  Nine finalists have been chosen in the essay c...
13  The clean room at NASA's Jet Propulsion Labora...
14  From rockets to rovers, JPL's Spacecraft Assem...
15  In a 10-plus-hour marathon, the rover steered,...
16  Researchers have created the first map of wind...
17  A type of Martian aurora first identified by N...
18  A new study identifies frozen water just below...
19  They look like twins. But under the hood, the ...
20  The twin spacecraft, the first of their kind t...
21  A Mars Dust Tower Stands Out Dust storms are c...
22  NASA and the Department of Energy have complet...
23  Apollo 12 and the upcoming Mars 2020 mission m...
24  Teams with NASA's Mars 2020 and ESA's ExoMars ...
25  For the first time in the history of space exp...
26  With the Mars 2020 mission ramping up, the doc...
27            Efforts to save the heat probe continue
28  In time-lapse video, taken at JPL, captures th...
29  The NASA rover performed a special chemistry e...
30  Want to name the robotic scientist NASA is sen...
31  In time-lapse video, bunny-suited engineers re...
32  New images taken from space offer the clearest...
33  New evidence suggests salty, shallow ponds onc...
34  A crane lifts the rocket-powered descent stage...

In [9]:
new_df = pd.concat([title_df, body_df], axis=1)
new_df

,title,Body
0,Virginia Middle School Student Earns Honor of...,NASA chose a seventh-grader from Virginia as w...
1,NASA's Curiosity Mars Rover Snaps Its Highest...,After a months-long contest among students to ...
2,NASA to Reveal Name of Its Next Mars Rover,A batch of new papers summarizes the lander's ...
3,The MarCO Mission Comes to an End,Engineers have a plan for pushing down on the ...
4,A Year of Surprising Science From NASA's InSi...,The following Q&amp;As with members of the tea...
5,Mars InSight Lander to Push on Top of the 'Mole',The leadership council for Mars 2020 science a...
6,Common Questions about InSight's 'Mole',Other orbiters will continue relaying data fro...
7,NASA Adds Return Sample Scientists to Mars 20...,The agency's first step in returning rocks fro...
8,NASA's Mars Reconnaissance Orbiter Undergoes ...,Robotic spacecraft will be able to communicate...
9,NASA's Mars 2020 Rover Goes Coast-to-Coast to...,Jim Bridenstine addresses NASA's ambitious pla...
10,NASA Prepares for Moon and Mars With New Addi...,SuperCam is a rock-vaporizing instrument that ...
11,NASA Administrator Statement on Moon to Mars ...,NASA’s MAVEN spacecraft has discovered “layers...
12,All About the Laser (and Microphone) Atop Mar...,Nine finalists have been chosen in the essay c...
13,NASA's MAVEN Explores Mars to Understand Radi...,The clean room at NASA's Jet Propulsion Labora...
14,Nine Finalists Chosen in NASA's Mars 2020 Rov...,"From rockets to rovers, JPL's Spacecraft Assem..."
15,NASA's Mars 2020 Rover Closer to Getting Its ...,"In a 10-plus-hour marathon, the rover steered,..."
16,Media Get a Close-Up of NASA's Mars 2020 Rover,Researchers have created the first map of wind...
17,Space History Is Made in This NASA Robot Factory,A type of Martian aurora first identified by N...
18,NASA's Mars 2020 Rover Completes Its First Drive,A new study identifies frozen water just below...
19,NASA's MAVEN Maps Winds in the Martian Upper ...,"They look like twins. But under the hood, the ..."
20,Newfound Martian Aurora Actually the Most Com...,"The twin spacecraft, the first of their kind t..."
21,NASA's Treasure Map for Water Ice on Mars,A Mars Dust Tower Stands Out Dust storms are c...
22,Two Rovers to Roll on Mars Again: Curiosity a...,NASA and the Department of Energy have complet...
23,NASA's Briefcase-Size MarCO Satellite Picks U...,Apollo 12 and the upcoming Mars 2020 mission m...
24,Global Storms on Mars Launch Dust Towers Into...,Teams with NASA's Mars 2020 and ESA's ExoMars ...
25,NASA Updates Mars 2020 Mission Environmental ...,For the first time in the history of space exp...
26,Two of a Space Kind: Apollo 12 and Mars 2020,"With the Mars 2020 mission ramping up, the doc..."
27,Mars Scientists Investigate Ancient Life in A...,Efforts to save the heat probe continue
28,NASA's Mars 2020 Will Hunt for Microscopic Fo...,"In time-lapse video, taken at JPL, captures th..."
29,Curiosity Serves Scientists a New One: Oxygen,The NASA rover performed a special chemistry e...
30,NASA's Mars 2020 Heads Into the Test Chamber,Want to name the robotic scientist NASA is sen...
31,Screening Soon: 'The Pathfinders' Trains Lens...,"In time-lapse video, bunny-suited engineers re..."
32,InSight's 'Mole' Team Peers into the Pit,New images taken from space offer the clearest...
33,Mars 2020 Stands on Its Own Six Wheels,"New evidence suggests salty, shallow ponds onc..."
34,Naming a NASA Mars Rover Can Change Your Life,A crane lifts the rocket-powered descent stage...

In [10]:
def scrape_nasa_image():
    browser = init_browser()

    # scrape nasa url
    url = "https://www.jpl.nasa.gov/spaceimages/?search=&category=Mars"
    browser.visit(url)

    time.sleep(3)

    # Scrape page into Soup
    html = browser.html
    soup = bs(html, "html.parser")

    # get article body
    image = soup.find('article', class_='carousel_item').get('style')
    
    # Close the browser after scraping
    browser.quit()

    # Return results
    return image

In [11]:
image = scrape_nasa_image()
image = image.replace("background-image: url();", "")

In [12]:
def scrape_tweets():
    browser = init_browser()

    # scrape nasa url
    url = "https://twitter.com/marswxreport?lang=en"
    browser.visit(url)

    time.sleep(3)

    # Scrape page into Soup
    html = browser.html
    soup = bs(html, "html.parser")

    # get article body
    tweet = soup.find_all('span', class_="css-901oao css-16my406 r-1qd0xha r-ad9z0x r-bcqeeo r-qvutc0")
    
    # Close the browser after scraping
    browser.quit()

    # Return results
    return tweet

In [13]:
tweet = scrape_tweets()

In [14]:
# function to remove html tags https://medium.com/@jorlugaqui/how-to-strip-html-tags-from-a-string-in-python-7cb81a2bbf44
def remove_html_tags(text):
    clean = re.compile('<.*?>')
    return re.sub(clean, '', text)
# call function and convert object to string using __repr__
tweet = remove_html_tags(tweet.__repr__())
tweet = tweet.split("·,")

In [15]:
tweet = pd.DataFrame(tweet)
tweet.columns = ['tweet']
tweet.drop(tweet.index[[0,1,2,4,5,6,7,8,9]], inplace=True)
tweet.reset_index(drop=True, inplace=True)
tweet

                                               tweet
0   InSight sol 457 (2020-03-10) low -95.7ºC (-14...

In [16]:
news_title = title_df.iloc[0]['title']
news_p = body_df.iloc[0]['Body']
featured_image_url = f"https://www.jpl.nasa.gov{image}"
mars_weather = tweet

In [17]:
def scrape_facts():
    browser = init_browser()

    # scrape nasa url
    url = "https://space-facts.com/mars/"
    browser.visit(url)

    time.sleep(3)

    # Scrape page into Soup
    html = browser.html
    soup = bs(html, "html.parser")

    # get article body
    facts = soup.find_all('tr')
    
    # Close the browser after scraping
    browser.quit()

    # Return results
    return facts

In [18]:
facts = scrape_facts()

In [19]:
facts

[<tr class="row-1 odd"><td class="column-1"><strong>Equatorial Diameter:</strong></td><td class="column-2">6,792 km<br/></td></tr>,
 <tr class="row-2 even"><td class="column-1"><strong>Polar Diameter:</strong></td><td class="column-2">6,752 km<br/></td></tr>,
 <tr class="row-3 odd"><td class="column-1"><strong>Mass:</strong></td><td class="column-2">6.39 × 10^23 kg<br/> (0.11 Earths)</td></tr>,
 <tr class="row-4 even"><td class="column-1"><strong>Moons:</strong></td><td class="column-2">2 (<a href="https://space-facts.com/moons/phobos/">Phobos</a> &amp; <a href="https://space-facts.com/moons/deimos/">Deimos</a>)</td></tr>,
 <tr class="row-5 odd"><td class="column-1"><strong>Orbit Distance:</strong></td><td class="column-2">227,943,824 km<br/> (1.38 AU)</td></tr>,
 <tr class="row-6 even"><td class="column-1"><strong>Orbit Period:</strong></td><td class="column-2">687 days (1.9 years)<br/></td></tr>,
 <tr class="row-7 odd"><td class="column-1"><strong>Surface Temperature: </strong></td><td class="column-2">-87 to -5 °C</td></tr>,
 <tr class="row-8 even"><td class="column-1"><strong>First Record:</strong></td><td class="column-2">2nd millennium BC</td></tr>,
 <tr class="row-9 odd"><td class="column-1"><strong>Recorded By:</strong></td><td class="column-2">Egyptian astronomers</td></tr>,
 <tr class="row-1"><th class="column-1"><strong>Mars - Earth Comparison</strong></th><th class="column-2"><span class="mars">Mars</span></th><th class="column-3"><span class="earth">Earth</span></th></tr>,
 <tr class="row-2"><td class="column-1">Diameter:</td><td class="column-2"><span class="mars-s">6,779 km</span></td><td class="column-3"><span class="earth-s">12,742 km</span></td></tr>,
 <tr class="row-3"><td class="column-1">Mass:</td><td class="column-2"><span class="mars-s">6.39 × 10^23 kg</span></td><td class="column-3"><span class="earth-s">5.97 × 10^24 kg</span></td></tr>,
 <tr class="row-4"><td class="column-1">Moons:</td><td class="column-2"><span class="mars-s">2</span></td><td class="column-3"><span class="earth-s">1</span></td></tr>,
 <tr class="row-5"><td class="column-1">Distance from Sun:</td><td class="column-2"><span class="mars-s">227,943,824 km</span></td><td class="column-3"><span class="earth-s">149,598,262 km</span></td></tr>,
 <tr class="row-6"><td class="column-1">Length of Year:</td><td class="column-2"><span class="mars-s">687 Earth days</span></td><td class="column-3"><span class="earth-s">365.24 days</span></td></tr>,
 <tr class="row-7"><td class="column-1">Temperature:</td><td class="column-2"><span class="mars-s">-153 to 20 °C</span></td><td class="column-3"><span class="earth-s">-88 to 58°C</span></td></tr>,
 <tr class="row-1 odd"><td class="column-1"><strong>Equatorial Diameter:</strong></td><td class="column-2">6,792 km<br/></td></tr>,
 <tr class="row-2 even"><td class="column-1"><strong>Polar Diameter:</strong></td><td class="column-2">6,752 km<br/></td></tr>,
 <tr class="row-3 odd"><td class="column-1"><strong>Mass:</strong></td><td class="column-2">6.39 × 10^23 kg<br/> (0.11 Earths)</td></tr>,
 <tr class="row-4 even"><td class="column-1"><strong>Moons:</strong></td><td class="column-2">2 (<a href="https://space-facts.com/moons/phobos/">Phobos</a> &amp; <a href="https://space-facts.com/moons/deimos/">Deimos</a>)</td></tr>,
 <tr class="row-5 odd"><td class="column-1"><strong>Orbit Distance:</strong></td><td class="column-2">227,943,824 km<br/> (1.38 AU)</td></tr>,
 <tr class="row-6 even"><td class="column-1"><strong>Orbit Period:</strong></td><td class="column-2">687 days (1.9 years)<br/></td></tr>,
 <tr class="row-7 odd"><td class="column-1"><strong>Surface Temperature: </strong></td><td class="column-2">-87 to -5 °C</td></tr>,
 <tr class="row-8 even"><td class="column-1"><strong>First Record:</strong></td><td class="column-2">2nd millennium BC</td></tr>,
 <tr class="row-9 odd"><td class="column-1"><strong>Recorded By:</strong></td><td class="column-2">Egyptian astronomers</td></tr>]

In [20]:
# function to remove html tags https://medium.com/@jorlugaqui/how-to-strip-html-tags-from-a-string-in-python-7cb81a2bbf44
def remove_html_tags(text):
    clean = re.compile('<.*?>')
    return re.sub(clean, '', text)
# call function and convert object to string using __repr__
facts = remove_html_tags(facts.__repr__())

In [21]:
facts

'[Equatorial Diameter:6,792 km, Polar Diameter:6,752 km, Mass:6.39 × 10^23 kg (0.11 Earths), Moons:2 (Phobos &amp; Deimos), Orbit Distance:227,943,824 km (1.38 AU), Orbit Period:687 days (1.9 years), Surface Temperature: -87 to -5 °C, First Record:2nd millennium BC, Recorded By:Egyptian astronomers, Mars - Earth ComparisonMarsEarth, Diameter:6,779 km12,742 km, Mass:6.39 × 10^23 kg5.97 × 10^24 kg, Moons:21, Distance from Sun:227,943,824 km149,598,262 km, Length of Year:687 Earth days365.24 days, Temperature:-153 to 20 °C-88 to 58°C, Equatorial Diameter:6,792 km, Polar Diameter:6,752 km, Mass:6.39 × 10^23 kg (0.11 Earths), Moons:2 (Phobos &amp; Deimos), Orbit Distance:227,943,824 km (1.38 AU), Orbit Period:687 days (1.9 years), Surface Temperature: -87 to -5 °C, First Record:2nd millennium BC, Recorded By:Egyptian astronomers]'

In [22]:
facts = facts.replace("[", "").split(", ")
facts_df = pd.DataFrame(facts)
facts_df.columns = ['facts']
facts_df = facts_df['facts'].str.split(":", expand = True)
facts_df.columns = ['Info', 'Data']
facts_df

                                Info                            Data
0                Equatorial Diameter                        6,792 km
1                     Polar Diameter                        6,752 km
2                               Mass   6.39 × 10^23 kg (0.11 Earths)
3                              Moons         2 (Phobos &amp; Deimos)
4                     Orbit Distance        227,943,824 km (1.38 AU)
5                       Orbit Period            687 days (1.9 years)
6                Surface Temperature                    -87 to -5 °C
7                       First Record               2nd millennium BC
8                        Recorded By            Egyptian astronomers
9   Mars - Earth ComparisonMarsEarth                            None
10                          Diameter               6,779 km12,742 km
11                              Mass  6.39 × 10^23 kg5.97 × 10^24 kg
12                             Moons                              21
13                 Distance from Sun    227,943,824 km149,598,262 km
14                    Length of Year       687 Earth days365.24 days
15                       Temperature        -153 to 20 °C-88 to 58°C
16               Equatorial Diameter                        6,792 km
17                    Polar Diameter                        6,752 km
18                              Mass   6.39 × 10^23 kg (0.11 Earths)
19                             Moons         2 (Phobos &amp; Deimos)
20                    Orbit Distance        227,943,824 km (1.38 AU)
21                      Orbit Period            687 days (1.9 years)
22               Surface Temperature                    -87 to -5 °C
23                      First Record               2nd millennium BC
24                       Recorded By           Egyptian astronomers]

In [23]:
def scrape_pics():
    browser = init_browser()

    # scrape nasa url
    url = "https://astrogeology.usgs.gov/search/results?q=hemisphere+enhanced&k1=target&v1=Mars"
    browser.visit(url)

    time.sleep(3)

    # Scrape page into Soup
    html = browser.html
    soup = bs(html, "html.parser")

    # get article body
    pics = soup.find_all('img', class_="thumb")
    
    # Close the browser after scraping
    browser.quit()

    # Return results
    return pics

In [24]:
pics = scrape_pics()

In [25]:
pics

[<img alt="Cerberus Hemisphere Enhanced thumbnail" class="thumb" src="/cache/images/dfaf3849e74bf973b59eb50dab52b583_cerberus_enhanced.tif_thumb.png"/>,
 <img alt="Schiaparelli Hemisphere Enhanced thumbnail" class="thumb" src="/cache/images/7677c0a006b83871b5a2f66985ab5857_schiaparelli_enhanced.tif_thumb.png"/>,
 <img alt="Syrtis Major Hemisphere Enhanced thumbnail" class="thumb" src="/cache/images/aae41197e40d6d4f3ea557f8cfe51d15_syrtis_major_enhanced.tif_thumb.png"/>,
 <img alt="Valles Marineris Hemisphere Enhanced thumbnail" class="thumb" src="/cache/images/04085d99ec3713883a9a57f42be9c725_valles_marineris_enhanced.tif_thumb.png"/>]

In [26]:
#last of the scrapes
news_title = title_df.iloc[0]['title']
news_p = body_df.iloc[0]['Body']
featured_image_url = f"https://www.jpl.nasa.gov{image}"
mars_weather = tweet
facts_df
mars_list = {
    "title" : "Cerberus Hemisphere", "img_url" : "/cache/images/dfaf3849e74bf973b59eb50dab52b583_cerberus_enhanced.tif_thumb.png",
    "title" : "Schiaparelli Hemisphere", "img_url" : "cache/images/7677c0a006b83871b5a2f66985ab5857_schiaparelli_enhanced.tif_thumb.png",
    "title" : "Syrtis Major", "img_url" : "/cache/images/aae41197e40d6d4f3ea557f8cfe51d15_syrtis_major_enhanced.tif_thumb.png",
    "title" : "Valles Marineris", "img_url" : "/cache/images/04085d99ec3713883a9a57f42be9c725_valles_marineris_enhanced.tif_thumb.png"
}